config:
  bind: 0.0.0.0:__PORT__
  onlineMode: true

  # 后端服务器列表：注意这里只能写 "名字: 地址"
  servers:
    hypixel: mc.hypixel.net:25565

  # 默认尝试顺序：只写名字
  try:
    - hypixel
  
  routes:
    - match: ".*"       # 匹配所有玩家
      servers: [hypixel]

  # MOTD / 状态信息
  status:
    motd: |
      §bCracky Boost
      §bPowered by Gate
    showMaxPlayers: 2025

  # Lite 模式
  lite:
    enabled: true
    routes:
      - host: "0.0.0.0:__PORT__"
        backend: mc.hypixel.net:25565
        fallback:
          motd: |
            §c666服务器暂时跑路了
            §e请稍后再试！
          version:
            name: '§cOffline'
            protocol: -1

  # 转发模式
  forwarding:
    mode: legacy

  proxyProtocol: false
  compression:
    threshold: 256
    level: -1
  connectionTimeout: 5s
  readTimeout: 30s
  failoverOnUnexpectedServerDisconnect: true
  onlineModeKickExistingPlayers: false
  debug: false
  verbosity: 0
  
