# Gate proxy configuration template

bind: 0.0.0.0:__PORT__
onlineMode: true

# Backend servers
servers: 
  hypixel: 
    address: mc.hypixel.net:25565
    motd: "Hypixel via Gate"
    version: "auto"

# Default try order
try:
  - hypixel: mc.hypixel.net:25565

# Status / MOTD
status:
  motd: |
    §bGate Proxy
    §bPowered by MineKube
  showMaxPlayers: 2025
  favicon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAA...
  logPingRequests: false
  announceForge: true

# Lite mode (full proxy enabled)
lite:
  enabled: false

# Forwarding / proxy protocol
forwarding:
  mode: legacy

proxyProtocol: false

compression:
  threshold: 256
  level: -1
connectionTimeout: 5s
readTimeout: 30s
failoverOnUnexpectedServerDisconnect: true
onlineModeKickExistingPlayers: false

debug: false
verbosity: 0

query:
  enabled: false
  port: 25577
  showPlugins: false
  