java:
  bind: 0.0.0.0:${PORT}
  onlineMode: true
  
  servers:
    hypixel: "mc.hypixel.net:25565"
    # backup: "mc.example.com:25565"   # 需要可以再加
    
  try:
    - hypixel
    
  status:
    motd: |
      §bGate Proxy
      §bPowered by MineKube
    showMaxPlayers: 2025
    announceForge: true
    
  # 其他可选项……
  lite:
    enabled: false
    