config:
  bind: 0.0.0.0:__PORT__
  onlineMode: true

  # 后端服务器列表：注意这里只能写 "名字: 地址"
  servers:
    hypixel: mc.hypixel.net:25565

  # 默认尝试顺序：只写名字
  try:
    - hypixel

  # MOTD / 状态信息
  status:
    motd: |
      §bGate Proxy
      §bPowered by MineKube
    showMaxPlayers: 2025

  # Lite 模式关掉
  lite:
    enabled: false

  # 转发模式
  forwarding:
    mode: legacy

  proxyProtocol: false
  compression:
    threshold: 256
    level: -1
  connectionTimeout: 5s
  readTimeout: 30s
  failoverOnUnexpectedServerDisconnect: true
  onlineModeKickExistingPlayers: false
  debug: false
  verbosity: 0
